#!/bin/bash

folders="satania
fumo
dantheman
booru_number_nekos
shinobu
energy_drink
yuu
eating_burgers
chito
anime_girls_holding_books
cirno
real_life
smug
yuru_yuri
yuu_koito
yagate
christ-chan
biting
sad
komi-san
nico
XD
hugs
r-tewi
commentfaces
videos
lewd"


for fol in ${folders}
do
		for ((  i=0; ; i++ ))
		do
			command="$(./gnuapi $fol $i)"
			echo $command
			$(curl $command > $fol$i.png)
			if [[ $? != 0  ]]; then
				break
			fi
		done
done

